# Generated by Django 3.1.3 on 2021-10-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211009_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='sample', max_length=10),
            preserve_default=False,
        ),
    ]
