# Generated by Django 3.1.3 on 2020-11-28 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='trashcan',
            name='user',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
