# Generated by Django 3.1.3 on 2021-11-05 18:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_auto_20211019_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='trashcan',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
