# Generated by Django 3.1.3 on 2021-11-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_trashcan_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrashcanDetection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='detection/')),
            ],
        ),
    ]
