# Generated by Django 3.1.3 on 2021-11-21 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_trashcandetection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trashcandetection',
            name='title',
        ),
    ]
