# Generated by Django 3.1.3 on 2021-11-21 16:28

from django.db import migrations, models
import location.models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0007_remove_trashcandetection_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trashcandetection',
            name='image',
            field=models.ImageField(blank=True, upload_to=location.models.detection_upload_to),
        ),
    ]
