# Generated by Django 3.1.3 on 2020-11-29 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0007_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='nickname',
        ),
    ]
