# Generated by Django 3.1.3 on 2020-11-29 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0008_remove_profile_nickname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
